### ISSUE TITLE
High-Low Frequency Decomposition and High-Low Frequency Interaction

### ISSUE THREAD

**Issue by xianming-gu** [BiQiWHU/BWG#1]
Dear author, I did not find the codes of "High-Low Frequency Decomposition" and "High-Low Frequency Interaction" part of the paper. Which python file are these in？

**Comment by BiQiWHU** [comment]
Hi there, thanks for your interest on this project!

You may find the Haar wavelet based operations at [https://github.com/BiQiWHU/BWG/blob/39ebe25c2d8c06c56d9b5a5d92ec962449d0fd98/mask2former/modeling/transformer_decoder/mask2former_transformer_decoder.py#L20].
