### ISSUE TITLE
evluate

### ISSUE THREAD

**Issue by leo-lab-511** [BiQiWHU/BWG#3]
when i evluate other  dataset(foggy-zurich)，i can not run succesfully ,if you modifiy the content of library file，can  you offer yours

**Comment by BiQiWHU** [comment]
Hi, thanks for your interest on this project. We directly covert the format of all the datasets into the format of the CityScapes, so that we can run train and inference with only a single loader.

**Comment by leo-lab-511** [comment]
can  you offer yours ,it's difficult for me to solve this problem
